
port: 4000
host: 0.0.0.0
safe: false


# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
highlighter:      pygments

# Permalinks
#permalink:        pretty
relative_permalinks: true

# Setup
title:            EnForce
tagline:          'EnForce tools for Salesforce'
description:      'EnForce tools for Salesforce that helps on development and Continuous Integration for Salesforce projects.'
url:              "http://enforce-gradle-plugin.github.io/sfdc-idea"
baseurl:          "/"
author:
  name:           'Jalasoft Inc.'
  url:            https://twitter.com/jalasoft

#paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Jalasoft/enforce-gradle-plugin

collections:
  docs:
    output: true
  home:
    output: true

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
#permalink: / ## disables post output
timezone: null
lsi: false


### content configuration ###
theme_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  green2:    '#63BD2F'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
